### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [Ramotion/adaptive-tab-bar#7]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by jiankian** [comment]
can you give me a swift3 version source?    i@asmm.cn  very Thanks!

**Comment by shallad** [comment]
is it available for Swift 3 ?

**Comment by ikolpachkov** [comment]
Source code updated to support Swift 4.0
